### ISSUE TITLE
Cannot set property cssText

### ISSUE THREAD

**Issue by wallat** [dodo/node-raphael#4]
HI, I installed your code and try run the sample code. But I got this error message

TypeError: Cannot set property cssText of [object Object] which has only a getter
    at Function.<anonymous> (/home/wallat/node_modules/raphael/raphael.js:1790:36)
    at R (/home/wallat/node_modules/raphael/raphael.js:19:28)
    at Object.<anonymous> (/home/wallat/www/jsdom/run.js:29:9)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)

My raphael version is 1.5.2 which is installed by npm. 
I found out the error line is: cnvs.style.cssText = "position:absolute;left:" + x + "px;top:" + y + "px";

Dose this error caused by jsdom only supports DOM1.0 ?

**Comment by wallat** [comment]
After giving the dom as first argument, it works.

**Comment by EvilFaeton** [comment]
@wallat What do you change in example script to get it work? Explain pls.

**Comment by dodo** [comment]
@EvilFaeton the example script doesn't work ?

**Comment by wallat** [comment]
@EvilFaeton I roughly remember that the error is that I directly give the jquery return object as the first argument. After change the first argument from $(xxx) into $(xxx)[0] it works fine. 

But it does not support some newer SVG format used by Raphael.
